export namespace Flag {
  export const OPENCODE_AUTO_SHARE = truthy("OPENCODE_AUTO_SHARE")
  export const OPENCODE_GIT_BASH_PATH = process.env["OPENCODE_GIT_BASH_PATH"]
  export const OPENCODE_CONFIG = process.env["OPENCODE_CONFIG"]
  export const OPENCODE_CONFIG_DIR = process.env["OPENCODE_CONFIG_DIR"]
  export const OPENCODE_CONFIG_CONTENT = process.env["OPENCODE_CONFIG_CONTENT"]
  export const OPENCODE_DISABLE_AUTOUPDATE = truthy("OPENCODE_DISABLE_AUTOUPDATE")
  export const OPENCODE_DISABLE_PRUNE = truthy("OPENCODE_DISABLE_PRUNE")
  export const OPENCODE_DISABLE_TERMINAL_TITLE = truthy("OPENCODE_DISABLE_TERMINAL_TITLE")
  export const OPENCODE_PERMISSION = process.env["OPENCODE_PERMISSION"]
  export const OPENCODE_DISABLE_DEFAULT_PLUGINS = truthy("OPENCODE_DISABLE_DEFAULT_PLUGINS")
  export const OPENCODE_DISABLE_LSP_DOWNLOAD = truthy("OPENCODE_DISABLE_LSP_DOWNLOAD")
  export const OPENCODE_ENABLE_EXPERIMENTAL_MODELS = truthy("OPENCODE_ENABLE_EXPERIMENTAL_MODELS")
  export const OPENCODE_DISABLE_AUTOCOMPACT = truthy("OPENCODE_DISABLE_AUTOCOMPACT")
  export const OPENCODE_DISABLE_MODELS_FETCH = truthy("OPENCODE_DISABLE_MODELS_FETCH")
  export const OPENCODE_FAKE_VCS = process.env["OPENCODE_FAKE_VCS"]
  export const OPENCODE_CLIENT = process.env["OPENCODE_CLIENT"] ?? "cli"

  // Experimental
  export const OPENCODE_EXPERIMENTAL = truthy("OPENCODE_EXPERIMENTAL")
  export const OPENCODE_EXPERIMENTAL_FILEWATCHER = truthy("OPENCODE_EXPERIMENTAL_FILEWATCHER")
  export const OPENCODE_EXPERIMENTAL_DISABLE_FILEWATCHER = truthy("OPENCODE_EXPERIMENTAL_DISABLE_FILEWATCHER")
  export const OPENCODE_EXPERIMENTAL_ICON_DISCOVERY =
    OPENCODE_EXPERIMENTAL || truthy("OPENCODE_EXPERIMENTAL_ICON_DISCOVERY")
  export const OPENCODE_EXPERIMENTAL_DISABLE_COPY_ON_SELECT = truthy("OPENCODE_EXPERIMENTAL_DISABLE_COPY_ON_SELECT")
  export const OPENCODE_ENABLE_EXA =
    truthy("OPENCODE_ENABLE_EXA") || OPENCODE_EXPERIMENTAL || truthy("OPENCODE_EXPERIMENTAL_EXA")
  export const OPENCODE_EXPERIMENTAL_BASH_MAX_OUTPUT_LENGTH = number("OPENCODE_EXPERIMENTAL_BASH_MAX_OUTPUT_LENGTH")
  export const OPENCODE_EXPERIMENTAL_BASH_DEFAULT_TIMEOUT_MS = number("OPENCODE_EXPERIMENTAL_BASH_DEFAULT_TIMEOUT_MS")
  export const OPENCODE_EXPERIMENTAL_OUTPUT_TOKEN_MAX = number("OPENCODE_EXPERIMENTAL_OUTPUT_TOKEN_MAX")
  export const OPENCODE_EXPERIMENTAL_OXFMT = OPENCODE_EXPERIMENTAL || truthy("OPENCODE_EXPERIMENTAL_OXFMT")
  export const OPENCODE_EXPERIMENTAL_LSP_TY = truthy("OPENCODE_EXPERIMENTAL_LSP_TY")

  // SWORDSMITH_ prefixed flags with OPENCODE_ fallback for backwards compatibility
  export const SWORDSMITH_AUTO_SHARE = truthy("SWORDSMITH_AUTO_SHARE") || OPENCODE_AUTO_SHARE
  export const SWORDSMITH_GIT_BASH_PATH = process.env["SWORDSMITH_GIT_BASH_PATH"] ?? OPENCODE_GIT_BASH_PATH
  export const SWORDSMITH_CONFIG = process.env["SWORDSMITH_CONFIG"] ?? OPENCODE_CONFIG
  export const SWORDSMITH_CONFIG_DIR = process.env["SWORDSMITH_CONFIG_DIR"] ?? OPENCODE_CONFIG_DIR
  export const SWORDSMITH_CONFIG_CONTENT = process.env["SWORDSMITH_CONFIG_CONTENT"] ?? OPENCODE_CONFIG_CONTENT
  export const SWORDSMITH_DISABLE_AUTOUPDATE = truthy("SWORDSMITH_DISABLE_AUTOUPDATE") || OPENCODE_DISABLE_AUTOUPDATE
  export const SWORDSMITH_DISABLE_PRUNE = truthy("SWORDSMITH_DISABLE_PRUNE") || OPENCODE_DISABLE_PRUNE
  export const SWORDSMITH_DISABLE_TERMINAL_TITLE =
    truthy("SWORDSMITH_DISABLE_TERMINAL_TITLE") || OPENCODE_DISABLE_TERMINAL_TITLE
  export const SWORDSMITH_PERMISSION = process.env["SWORDSMITH_PERMISSION"] ?? OPENCODE_PERMISSION
  export const SWORDSMITH_DISABLE_DEFAULT_PLUGINS =
    truthy("SWORDSMITH_DISABLE_DEFAULT_PLUGINS") || OPENCODE_DISABLE_DEFAULT_PLUGINS
  export const SWORDSMITH_DISABLE_LSP_DOWNLOAD =
    truthy("SWORDSMITH_DISABLE_LSP_DOWNLOAD") || OPENCODE_DISABLE_LSP_DOWNLOAD
  export const SWORDSMITH_ENABLE_EXPERIMENTAL_MODELS =
    truthy("SWORDSMITH_ENABLE_EXPERIMENTAL_MODELS") || OPENCODE_ENABLE_EXPERIMENTAL_MODELS
  export const SWORDSMITH_DISABLE_AUTOCOMPACT =
    truthy("SWORDSMITH_DISABLE_AUTOCOMPACT") || OPENCODE_DISABLE_AUTOCOMPACT
  export const SWORDSMITH_DISABLE_MODELS_FETCH =
    truthy("SWORDSMITH_DISABLE_MODELS_FETCH") || OPENCODE_DISABLE_MODELS_FETCH
  export const SWORDSMITH_FAKE_VCS = process.env["SWORDSMITH_FAKE_VCS"] ?? OPENCODE_FAKE_VCS
  export const SWORDSMITH_CLIENT = process.env["SWORDSMITH_CLIENT"] ?? OPENCODE_CLIENT

  // SWORDSMITH_ Experimental flags with OPENCODE_ fallback
  export const SWORDSMITH_EXPERIMENTAL = truthy("SWORDSMITH_EXPERIMENTAL") || OPENCODE_EXPERIMENTAL
  export const SWORDSMITH_EXPERIMENTAL_FILEWATCHER =
    truthy("SWORDSMITH_EXPERIMENTAL_FILEWATCHER") || OPENCODE_EXPERIMENTAL_FILEWATCHER
  export const SWORDSMITH_EXPERIMENTAL_DISABLE_FILEWATCHER =
    truthy("SWORDSMITH_EXPERIMENTAL_DISABLE_FILEWATCHER") || OPENCODE_EXPERIMENTAL_DISABLE_FILEWATCHER
  export const SWORDSMITH_EXPERIMENTAL_ICON_DISCOVERY =
    SWORDSMITH_EXPERIMENTAL || truthy("SWORDSMITH_EXPERIMENTAL_ICON_DISCOVERY") || OPENCODE_EXPERIMENTAL_ICON_DISCOVERY
  export const SWORDSMITH_EXPERIMENTAL_DISABLE_COPY_ON_SELECT =
    truthy("SWORDSMITH_EXPERIMENTAL_DISABLE_COPY_ON_SELECT") || OPENCODE_EXPERIMENTAL_DISABLE_COPY_ON_SELECT
  export const SWORDSMITH_ENABLE_EXA =
    truthy("SWORDSMITH_ENABLE_EXA") ||
    SWORDSMITH_EXPERIMENTAL ||
    truthy("SWORDSMITH_EXPERIMENTAL_EXA") ||
    OPENCODE_ENABLE_EXA
  export const SWORDSMITH_EXPERIMENTAL_BASH_MAX_OUTPUT_LENGTH =
    number("SWORDSMITH_EXPERIMENTAL_BASH_MAX_OUTPUT_LENGTH") ?? OPENCODE_EXPERIMENTAL_BASH_MAX_OUTPUT_LENGTH
  export const SWORDSMITH_EXPERIMENTAL_BASH_DEFAULT_TIMEOUT_MS =
    number("SWORDSMITH_EXPERIMENTAL_BASH_DEFAULT_TIMEOUT_MS") ?? OPENCODE_EXPERIMENTAL_BASH_DEFAULT_TIMEOUT_MS
  export const SWORDSMITH_EXPERIMENTAL_OUTPUT_TOKEN_MAX =
    number("SWORDSMITH_EXPERIMENTAL_OUTPUT_TOKEN_MAX") ?? OPENCODE_EXPERIMENTAL_OUTPUT_TOKEN_MAX
  export const SWORDSMITH_EXPERIMENTAL_OXFMT =
    SWORDSMITH_EXPERIMENTAL || truthy("SWORDSMITH_EXPERIMENTAL_OXFMT") || OPENCODE_EXPERIMENTAL_OXFMT
  export const SWORDSMITH_EXPERIMENTAL_LSP_TY =
    truthy("SWORDSMITH_EXPERIMENTAL_LSP_TY") || OPENCODE_EXPERIMENTAL_LSP_TY

  function truthy(key: string) {
    const value = process.env[key]?.toLowerCase()
    return value === "true" || value === "1"
  }

  function number(key: string) {
    const value = process.env[key]
    if (!value) return undefined
    const parsed = Number(value)
    return Number.isInteger(parsed) && parsed > 0 ? parsed : undefined
  }
}
